// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:0d85b9e8-4512-4615-a4ca-5a9fc7aa2fba",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_U4EWm5GF0",
    "aws_user_pools_web_client_id": "4sd1ager39g14f8082bh2rlvga",
    "aws_user_files_s3_bucket": "planitc3c7c293de314bf1a52e33081e2587da",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
